version: '3'

services:
  django-backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - "8000:8000"

  react-frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend/ati-2-frontend
        target: /app
    ports:
      - "5173:5173"
    environment:
      # - DJANGO_API_URL=http://localhost:8000
      - DJANGO_API_URL=http://3.137.150.119:8000

