### ---- USUARIOS ----
POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "bank_country" : "",
    "bank_origin" : "xxxxxx",
    "cellphone" : "11111",
    "client_code" : "388455139",
    "contact_email" : "xxxx@gmail.com",
    "country" : "",
    "dni" : "xxxxxxxx",
    "email" : "ati3@gmail.com",
    "email_to_inform" : "x",
    "facebook_to_inform" : "",
    "first_name" : "xxxxxxx",
    "found_app_by" : {"website": true, "friends": false},
    "frecuency_to_inform" : "mensual",
    "language" : "es",
    "last_name" : "xxxx",
    "other_to_inform" : "",
    "password" : "xxxxxxxxxxx",
    "phone_to_inform" : "",
    "services_interest" : {"available_personal": true, "professional_advice": false},
    "social_media_to_inform" : {"Facebook": false, "Twitter": false},
    "type_user" : "natural",
    "want_inform" : true
}
###
POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "email": "andrea65@gmail.com",
    "password": "12345",
    "found_app_by": "Facebook",
    "type_user": "natural",
    "country": "Polonia",
    "first_name": "Andrea",
    "last_name": "Lopez",
    "dni": "FS4240062",
    "contact_email": "andrea65@gmail.com",
    "language": "en",
    "want_inform": false,
    "bank_origin": "Santander",
    "bank_country": "Polonia"
}

###
POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "email": "vargas@gmail.com",
    "password": "12345",
    "found_app_by": "Twitter",
    "type_user": "enterprise",
    "country": "Venezuela",
    "companty_name": "Babysits",
    "rif": "F126125",
    "city": "Caracas",
    "language": "es",
    "bank_origin": "Banesco",
    "bank_country": "Venezuela",
    "want_inform": true, 
    "social_media_to_inform": {
        "Facebook": true,
        "Twitter": false
    }
}

### ---- FORMATO PARA LAS REQUEST A AUTH-TOKEN ---- 
POST http://localhost:8000/token-auth/
content-type: application/json

{
    "username": "ati2.proyecto+carlos99@gmail.com",
    "password": "12345"
}

### ---- FORMATO PARA LAS REQUEST A UNIQUE_EMAIL ---- 
POST http://127.0.0.1:8000/users/unique_email/
content-type: application/json

{
    "email": "carlos99@gmail.com"
}

### ---- FORMATO PARA LAS REQUEST A GET_NAME ---- 
POST http://127.0.0.1:8000/users/get_name/
content-type: application/json

{
    "id": 6
}
###

POST http://127.0.0.1:8000/users/get_email/
content-type: application/json

{
    "id": 11
}


### ---- BANKS ----
POST http://127.0.0.1:8000/banks/
content-type: application/json

{
    "name": "Banesco Panamá",
    "account" : "201800948693",
    "swift_code" : "BANSPAPA",
    "country": "Panamá"
}

###
GET http://127.0.0.1:8000/banks/


### ----  A) Ofrecer mis servicios como personal domestico ---- 
POST http://127.0.0.1:8000/api-services/provideService/post_ad/
Authorization: Token a64c87a4ff096c01bef71b1c9d8dc5445b578ec6
content-type: application/json

{
    "user": 11, 
    "service": "NIN", 
    "age": 29,
    "have_children": false,
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "CO",
    "state": "Barranquilla",
    "city": "Santa Rosa",
    "zone": "La Pastora",
    "description": "Persona con 8 años en experiencia en el cuidado de adultos mayores",
    "travel": false,
    "travel_decription": "",
    "activities": "Preparación de alimentos, Jugar con los niños, Limpieza del hogar",
    "workday": "INTERDIARIO",
    "workday_other": "",
    "schedule": ["LUN", "MAR"], 
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 85.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 1,
    "benefits_description": "Seguro social obligatorio, Póliza de HCM y cobertura a mis familiares, Ayuda para útiles escolares, Otros",
    "availability": "FECHA",
    "availability_date": "2023-06-12",
    "origin": "SI",
    "origin_continent": "Norteamerica",
    "origin_country": "Estados Unidos",
    "origin_state": "California",
    "origin_city": "San Jose",
    "client_type": "NO",
    "have_documentation": true,
    "documents": "CONST_RESIDENCIA",
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "1",
    "billing_country": "Venezuela",
    "billing_bank": "Banesco"
}

### 
POST http://127.0.0.1:8000/api-services/provideService/post_ad/
Authorization: Token 4e6ba7f9907e31bd1a0fdd3d209150b6c9cac595
content-type: application/json

{
    "user": 11, 
    "service": "CUI", 
    "age": 31,
    "have_children": false,
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "Colombia",
    "state": "Barranquilla",
    "city": "Santa Rosa",
    "zone": "La Pastora",
    "description": "Persona con 3 años en experiencia en el cuidado de niños",
    "travel": false,
    "travel_decription": "",
    "activities": "Preparación de alimentos, Control de medicamentos, Baño e higiene, Cambio de pañal",
    "workday": "INTERDIARIO",
    "workday_other": "",
    "schedule": "LUN",
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 115.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 1,
    "benefits_description": "Seguro social obligatorio, Póliza de HCM y cobertura a mis familiares, Ayuda para útiles escolares, Otros",
    "availability": "FECHA",
    "availability_date": "2023-06-22",
    "origin": "SI",
    "origin_continent": "Norteamerica",
    "origin_country": "Estados Unidos",
    "origin_state": "California",
    "origin_city": "San Jose",
    "client_type": "NO",
    "have_documentation": true,
    "documents": "CONST_RESIDENCIA",
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "1",
    "billing_country": "Venezuela",
    "billing_bank": 2
}

### B - Solicitar personal domestico
POST http://127.0.0.1:8000/api-services/requestService/post_ad/
Authorization: Token a64c87a4ff096c01bef71b1c9d8dc5445b578ec6
content-type: application/json

{
    "user": 11, 
    "service": "CUI",
    "gender": "IDC",
    "age_required_from": 18,
    "age_required_to": 26,
    "children": "IDC",
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "VE",
    "state": "Carabobo",
    "city": "San Diego",
    "zone": "El Calabozo",
    "number_tco": 2,
    "age_tco": "18 y 25",
    "gender_tco": "Femenino",
    "disabilities_tco": true,
    "disabilities_tco_decrip": "Una persona no puede caminar y la otra persona tiene problemas de audición",
    "diseases_tco_descrip": "Uno de ellos tiene ACV,  El médico ya le indicó su tratamiento. La otra persona no puede caminar, pero todos los días una persona debe venir a realizarse sus terapias para que poco a poco vaya recuperando la movilidad", 
    "travel": true,
    "travel_decription": "La persona debe estar dispuesta a viajar 1 vez al mes al exterior",
    "activities": "Limpiar",
    "workday": "SEMANAL",
    "workday_other": "",
    "schedule": ["LUN", "MIE"], 
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 30.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 1,
    "benefits_description": "Seguro social obligatorio, Póliza de HCM y cobertura a mis familiares, Ayuda para útiles escolares,  Otros",
    "availability": "FECHA",
    "availability_date": "2023-05-27",
    "have_documentation": true,
    "documents": ["REF_FAMILIAR", "PASAPORTE"],
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "3",
    "billing_country": "Venezuela",
    "billing_bank": 2
}

###

POST http://127.0.0.1:8000/api-services/requestService/post_ad/
Authorization: Token a64c87a4ff096c01bef71b1c9d8dc5445b578ec6
content-type: application/json

{
    "user": 11, 
    "service": "NIN",
    "gender": "IDC",
    "age_required_from": 10,
    "age_required_to": 12,
    "children": "IDC",
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "VE",
    "state": "Carabobo",
    "city": "San Diego",
    "zone": "El Calabozo",
    "number_tco": 2,
    "age_tco": "25 y 31",
    "gender_tco": "Femenino",
    "disabilities_tco": true,
    "disabilities_tco_decrip": "Un niño no puede caminar",
    "diseases_tco_descrip": "Todos los días una persona debe venir a realizarse sus terapias para que poco a poco vaya recuperando la movilidad", 
    "travel": true,
    "travel_decription": "La persona debe estar dispuesta a viajar 1 vez al mes al exterior",
    "activities": "Limpiar",
    "workday": "SEMANAL",
    "workday_other": "",
    "schedule": ["LUN", "MIE"], 
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 50.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 1,
    "benefits_description": "Seguro social obligatorio, Póliza de HCM y cobertura a mis familiares, Ayuda para útiles escolares,  Otros",
    "availability": "FECHA",
    "availability_date": "2023-08-02",
    "have_documentation": true,
    "documents": ["REF_FAMILIAR", "PASAPORTE"],
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "3",
    "billing_country": "Venezuela",
    "billing_bank": 2
}

### C - Buscar personal doméstico 
# Búsqueda : ?field__in=valor,valor&field=valor
# Ordenar: ?ordering=field
GET http://127.0.0.1:8000/api-services/provideService/?country=Venezuela
Authorization: Token 4c8522bf15678b3683239cb5d61bd3934aae3878


### D - Buscar clientes 
# Búsqueda : ?field__in=valor,valor&field=valor
# Ordenar: ?ordering=field
GET http://127.0.0.1:8000/api-services/requestService/?country=Venezuela
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Ver mis publicaciones {user_id}
### Ofrecer/Provide 
GET http://127.0.0.1:8000/api-services/provideService/2/
Authorization: Token 4c8522bf15678b3683239cb5d61bd3934aae3878

### Solicitar/Request 
GET http://127.0.0.1:8000/api-services/requestService/2/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Ver publicaciones de otros 
### Ofrecer/Provide
GET http://127.0.0.1:8000/api-services/provideService/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Solicitar/Provide
GET http://127.0.0.1:8000/api-services/requestService/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Ver detalles: {id}: 
### Ofrecer/Provide
GET http://localhost:8000/api-services/provide/get_post/dd14ae5c-fdc5-46a9-a826-df7f9a4f8f72/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Solicitar/Request
GET http://localhost:8000/api-services/request/get_post/bc09db74-2809-4051-896a-96ab7ed8b7a8/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Habilitar/Deshabilitar publicación
### Ofrecer/Provide
PUT http://localhost:8000/api-services/provide/enable_post/dd14ae5c-fdc5-46a9-a826-df7f9a4f8f73/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Solicitar/Request
PUT http://localhost:8000/api-services/request/enable_post/bc09db74-2809-4051-896a-96ab7ed8b7a8/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Update
### Ofrecer/Provide
PUT http://localhost:8000/api-services/provide/update_post/dd14ae5c-fdc5-46a9-a826-df7f9a4f8f72/
Authorization: Token a64c87a4ff096c01bef71b1c9d8dc5445b578ec6
content-type: application/json

{
    "user": 11, 
    "service": "CUI", 
    "age": 30,
    "have_children": false,
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "CO",
    "state": "Barranquilla",
    "city": "Santa Rosa",
    "zone": "",
    "description": "Decripción del perfil laboral",
    "travel": false,
    "travel_decription": "",
    "activities": "Cocinar",
    "workday": "QUINCENAL",
    "workday_other": "",
    "schedule": "LUN",
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 70.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 0,
    "benefits_description": "",
    "availability": "FECHA",
    "availability_date": "2023-10-02",
    "origin": "NO",
    "origin_continent": "",
    "origin_country": "",
    "origin_state": "",
    "origin_city": "",
    "client_type": "NO",
    "have_documentation": true,
    "documents": "CONST_RESIDENCIA",
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "1",
    "billing_country": "Venezuela",
    "billing_bank": 1
}

### Solicitar/Request
PUT http://localhost:8000/api-services/request/update_post/bc09db74-2809-4051-896a-96ab7ed8b7a8/
Authorization: Token a64c87a4ff096c01bef71b1c9d8dc5445b578ec6
content-type: application/json

{
    "user": 11, 
    "service": "CUI",
    "gender": "IDC",
    "age_required_from": 13,
    "age_required_to": 13,
    "children": "IDC",
    "education_level": "PRI",
    "continent": "Suramerica", 
    "country": "VE",
    "state": "Carabobo",
    "city": "San Diego de La Vega",
    "zone": "",
    "number_tco": 2,
    "age_tco": 11,
    "gender_tco": "Femenino",
    "disabilities_tco": true,
    "disabilities_tco_decrip": "Descripción de la Enfermedad",
    "travel": true,
    "travel_decription": "Descripción de las condiciones para viajar",
    "activities": "Limpiar",
    "workday": "SEMANAL",
    "workday_other": "",
    "schedule": "LUN",
    "schedule_other": "",
    "payment": "MONTO",
    "payment_amount": 30.00,
    "currency": "USD",
    "currency_other": "",
    "salary_offered": "HORA",
    "benefits": 0,
    "benefits_description": "",
    "availability": "FECHA",
    "availability_date": "2023-05-27",
    "have_documentation": false,
    "documents": "",
    "documents_other": "",
    "publication_time": "1",
    "publication_plan": "1",
    "billing_country": "Venezuela",
    "billing_bank": 1
}

### Delete {id}: 
### Ofrecer/Provide
DELETE http://127.0.0.1:8000/api-services/provide/delete_post/9f989823-ea54-40af-b379-198633fdaa79/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856

### Solicitar/Request
DELETE http://127.0.0.1:8000/api-services/request/delete_post/b57e824d-190c-423b-b550-21966bdfb846/
Authorization: Token c0cf83709dcf55b15767dde6905c2515854e6856




###
POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "email": "diegochz98@gmail.com",
    "password": "12345",
    "found_app_by": "Twitter",
    "type_user": "enterprise",
    "country": "Venezuela",
    "companty_name": "Compañia Admin",
    "dni": "26343836",
    "rif": "F123456",
    "city": "Caracas",
    "language": "es",
    "bank_origin": "Banesco",
    "bank_country": "Venezuela",
    "want_inform": true, 
    "social_media_to_inform": {
        "Facebook": true,
        "Twitter": false
    }
}

###
GET http://127.0.0.1:8000/users/14
Authorization: Token 6ba4807aa91fa9f95a9c696e003f42b2473d8863

###
POST http://127.0.0.1:8000/forgot-password/
content-type: application/json

{
    "email": "diegochz98@gmail.com",
    "dni": "26343836"
}

###

POST http://localhost:8000/token-auth/
content-type: application/json

{
    "username": "diegochz98@gmail.com",
    "password": "123456"
}

###
POST http://127.0.0.1:8000/users/14/change_password/
content-type: application/json

{
    "new_password": "123456",
    "confirm_password": "123456"
}