POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "email": "admin2@gmail.com",
    "password": "12345",
    "found_app_by": "Twitter",
    "type_user": "natural",
    "country": "Alemania",
    "first_name": "Admin",
    "last_name": "Ati-2",
    "dni": "V-126125",
    "contact_email": "admin@gmail.com",
    "language": "es"
}
###
POST http://127.0.0.1:8000/users/
content-type: application/json

{
    "email": "admin-company@gmail.com",
    "password": "12345",
    "found_app_by": "Twitter",
    "type_user": "enterprise",
    "country": "Venezuela",
    "companty_name": "Compañia Admin",
    "rif": "F126125",
    "city": "Caracas",
    "language": "es"
}

###
GET http://127.0.0.1:8000/users/2
Authorization: Token b42fe9ebbc307f42f06e55736ad3740736c2bf0a

### Formato para las request a AUTH-TOKEN
POST http://localhost:8000/token-auth/
content-type: application/json

{
    "username": "admin@gmail.com",
    "password": "1234"
}