# Generated by Django 4.1.8 on 2023-06-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="country",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
