# Generated by Django 4.1.8 on 2023-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('have_children', models.BooleanField()),
                ('education_level', models.CharField(choices=[('PRI', 'Primaria'), ('TEC', 'Técnico Univeristario'), ('BAC', 'Bachillerato'), ('UNI', 'Universitario')], max_length=3)),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('zone', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('travel', models.BooleanField()),
                ('travel_decription', models.TextField(blank=True)),
                ('activities', models.TextField()),
                ('workday', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('INTERDIARIO', 'Interdiario'), ('MEDIO_TIEMPO', 'Medio tiempo'), ('FIN_SEMANA', 'Fin de Semana'), ('NOCHE', 'En la noche'), ('HORAS', 'Por horas'), ('OTRO', 'Otro')], max_length=15)),
                ('workday_other', models.TextField(blank=True)),
                ('schedule', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo'), ('LUN_VIE', 'De Lunes a Viernes'), ('FIN', 'Fin de semana'), ('OTRO', 'Otros a considerar')], max_length=7)),
                ('schedule_other', models.TextField(blank=True)),
                ('payment', models.CharField(choices=[('MONTO', 'Monto'), ('CONVENIR', 'A convenir')], max_length=8)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('OTRA', 'Otra')], max_length=4)),
                ('currency_other', models.TextField(blank=True)),
                ('salary_offered', models.CharField(choices=[('HORA', 'Por hora'), ('DIA', 'Por dia'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=9)),
                ('benefits', models.BooleanField()),
                ('benefits_description', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('FECHA', 'Fecha de Inicio'), ('CONVENIR', 'A convenir')], max_length=8)),
                ('availability_date', models.DateField(blank=True)),
                ('origin', models.CharField(choices=[('NO', 'Me es indiferente'), ('SI', 'Quiero especificar la procedencia del cliente')], max_length=2)),
                ('origin_continent', models.TextField(blank=True)),
                ('origin_country', models.TextField(blank=True)),
                ('origin_state', models.TextField(blank=True)),
                ('origin_city', models.TextField(blank=True)),
                ('client_type', models.CharField(blank=True, choices=[('NAT', 'Natural'), ('EMP', 'Empresa'), ('NO', 'Me es indiferente si es persona natural o empresa')], max_length=3)),
                ('have_documentation', models.BooleanField()),
                ('documents', models.CharField(blank=True, choices=[('PASAPORTE', 'Documento de identidad o pasaporte'), ('CURRICULUM', 'Currículum actualizado'), ('TITULOS', 'Títulos o certificados'), ('REF_TRABAJO', 'Referencias comprobables de trabajo'), ('REF_FAMILIAR', 'Referencias familiares indicando nombre y apellido, teléfono local, Teléfono móvil, correo electrónico (opcional), y dirección'), ('CONST_RESIDENCIA', 'Constancia de residencia'), ('CONST_ANTECEDENTES', 'Constancia de no poseer antecedentes penales'), ('SALUD', 'Certificado de salud'), ('OTRO', 'Otro documento')], max_length=18)),
                ('documents_other', models.TextField(blank=True)),
                ('publication_time', models.CharField(choices=[('1', '1 mes'), ('3', '3 meses'), ('6', '6 meses'), ('9', '9 meses'), ('12', '12 meses')], max_length=2)),
                ('publication_plan', models.CharField(choices=[('1', '1 mes'), ('3', '3 meses'), ('6', '6 meses'), ('9', '9 meses'), ('12', '12 meses')], max_length=2)),
                ('billing_country', models.TextField()),
                ('billing_bank', models.TextField()),
            ],
        ),
    ]
