# Generated by Django 4.1.8 on 2023-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestservice",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEM", "Femenino"),
                    ("MAS", "Masculino"),
                    ("IDC", "Me es indiferente su sexo"),
                ],
                max_length=3,
            ),
        ),
    ]
