# Generated by Django 4.1.8 on 2023-06-11 03:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_requestservice_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provideservice",
            name="workday",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("SEMANAL", "Semanal"),
                    ("QUINCENAL", "Quincenal"),
                    ("MENSUAL", "Mensual"),
                    ("INTERDIARIO", "Interdiario"),
                    ("MEDIO_TIEMPO", "Medio tiempo"),
                    ("FIN_SEMANA", "Fin de Semana"),
                    ("NOCHE", "En la noche"),
                    ("HORAS", "Por horas"),
                    ("OTRO", "Otro"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="requestservice",
            name="workday",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("SEMANAL", "Semanal"),
                    ("QUINCENAL", "Quincenal"),
                    ("MENSUAL", "Mensual"),
                    ("INTERDIARIO", "Interdiario"),
                    ("MEDIO_TIEMPO", "Medio tiempo"),
                    ("FIN_SEMANA", "Fin de Semana"),
                    ("NOCHE", "En la noche"),
                    ("HORAS", "Por horas"),
                    ("OTRO", "Otro"),
                ],
                max_length=15,
            ),
        ),
    ]
