# Generated by Django 4.1.8 on 2023-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_found_app_by_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("es", "Spanish"), ("en", "English")], max_length=2
            ),
        ),
    ]
