# Generated by Django 4.1.8 on 2023-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="found_app_by",
            field=models.CharField(max_length=256),
        ),
    ]
